### Add Job Application (POST /job-application/add)
POST http://localhost/job-application/add
Content-Type: application/json

{
  "company": "Tech Company",
  "position": "Software Engineer",
  "details": "A description of the job.",
  "comment": ""
}

### Schedule Job Application Interview (POST /job-application/interview/schedule)
POST http://localhost/job-application/interview/schedule
Content-Type: application/json

{
  "id": "e1341355-6f66-4f31-9812-d1a1927191e4",
  "scheduleDate": "2025-02-28 12:00",
  "interviewType": "Other",
  "comment": ""
}

### Job Application Interview Was Held (POST /job-application/interview/held)
POST http://localhost/job-application/interview/held
Content-Type: application/json

{
  "id": "e1341355-6f66-4f31-9812-d1a1927191e4",
  "interviewId": "84dd6866-b474-4b2b-8326-c8e32c5e8ddf",
  "comment": ""
}

### Submit Job Application (POST /job-application/submit)
POST http://localhost/job-application/submit
Content-Type: application/json

{
  "id": "e1341355-6f66-4f31-9812-d1a1927191e4",
  "submitDate": "2025-02-28 12:00",
  "comment": "Excited about this opportunity!"
}

### Get Job Application (GET /job-application/list)
GET http://localhost/job-application/list

### Get Job Application details (GET /job-application/{id})
GET http://localhost/job-application/{id}
