openapi: 3.0.0
info:
  title: Job Search Assistant
  version: 0.2.0
  description: Assistant for jobseekers. Stores data and status of submitted job applications
servers:
  - url: http://localhost:8000
    description: Lokalny serwer developerski

paths:
  /job-application/add:
    post:
      summary: Add Job Application
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddJobInput'
      responses:
        '201':
          description: Job application added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddJob'
  /job-application/{id}:
    get:
      summary: Get single job application by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: A single job application with its history of events
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_application:
                    $ref: '#/components/schemas/JobApplication'
                  events:
                    type: array
                    items:
                      $ref: '#/components/schemas/JobApplicationEvent'
  /job-application/list:
    get:
      summary: Get list of Job Applications
      responses:
        '200':
          description: A list of job applications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetJob'


components:
  schemas:
    AddJobInput:
      type: object
      properties:
        "company":
          type: string
          example: "Tech Company"
        "position":
          type: string
          example: "Software Engineer"
        "details":
          type: string
          example: "A description of the job."
        "comment":
          type: string
          example: ""
    AddJob:
      type: object
      properties:
        "message":
          type: string
          example: "Job application added successfully"
        "id":
          type: string
          example: "9fd887af-e935-41e4-bd1e-d0e7e4057ccb"
    GetJob:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "cea17e23-3d4e-437c-8325-3ce321a2bf0d"
        company:
          type: string
          example: "Company"
        submitDate:
          type: string
          format: date-time
          example: "2025-03-07 12:25"
        eventName:
          type: string
          example: "job_application_submitted"
        comment:
          type: string
          example: "Example comment"
    JobApplication:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "288de407-d956-40c0-8da2-47a5f30bcb6d"
        company:
          type: string
          example: "Company"
        position:
          type: string
          example: "PHP dev"
        details:
          type: string
          example: "Detailed job application info..."
        submitDate:
          type: string
          example: "2025-01-01 16:00"
        comment:
          type: string
          example: "Example comment."
        status:
          type: string
          example: "job_application_submitted"
    JobApplicationEvent:
      type: object
      properties:
        event_name:
          type: string
          example: "job_application_submitted"
        version:
          type: integer
          example: 1
        occurred_at:
          type: string
          example: "2025-01-01 23:00"
        data:
          type: string
          description: JSON string representing the event data
        comment:
          type: string
          nullable: true
          example: "Example comment"
